### ISSUE TITLE
Timer

### ISSUE THREAD

**Issue by nelsong6** [NelsonRomaine/Genetic-algorithm-8queens#1]
Should have a timer to help keep track of how much progress is being made while generating the listboxes.

**Comment by nelsong6** [comment]
Listbox 3 should be titled "Child 1", and listbox 4 should be titled" "Child 2"

**Comment by nelsong6** [comment]
The comboboxes in groupboxes "population size", "mutation", and "iterate", could be simplified to not have either button, and accept input on value change instead.

These comboboxes also could be changed to accept input from the enter key.

**Comment by NelsonRomaine** [comment]
The initial settings groupbox is redundant, as
